name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Railway
        uses: railwayapp/actions@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
